project:
  type: website

website:
  title: "Workflow"
  navbar:
    left:
      - href: index.qmd
        text: Workflow
      - href: report.qmd
        text: Report

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



